<a href="https://colab.research.google.com/github/printbackslashn/ColabDatascience/blob/main/LearningDatascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


About numpy

Numerical python


Arrays in numpys,



1. np.array
> Standard array

2. np.ones
> All array values are set to 1, and a certain type.
> Select y axis than x axis
3. np.full
>
4. np.arange
5. np.linspace
6. np.random.rand
7. np.empty


In [11]:
numpyArray = np.array([1, 2, 3])
print(type(numpyArray))
print(f"The array is {numpyArray}")
print(f"0 in the array is {numpyArray[0]}")
print(f"1 in the array is {numpyArray[1]}")
print(f"2 in the array is {numpyArray[2]}")
print(f"-1 in the array is {numpyArray[-1]}")

<class 'numpy.ndarray'>
The array is [1 2 3]
0 in the array is 1
1 in the array is 2
2 in the array is 3
-1 in the array is 3


In [12]:
numpyOnes = np.ones( (3,4),
                    dtype=np.int16 )
print(numpyOnes)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
