<a href="https://colab.research.google.com/github/printbackslashn/ColabDatascience/blob/main/LearningDatascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


About numpy

Numerical python


Arrays in numpys,



1. np.array
> Standard array

2. np.ones
> All array values are set to 1, and a certain type.
> Select y axis than x axis
3. np.full
>
4. np.arange
5. np.linspace
6. np.random.rand
7. np.empty


In [ ]:
numpyArray = np.array([1, 2, 3])
print(type(numpyArray))
print(f"The array is {numpyArray}")
print(f"0 in the array is {numpyArray[0]}")
print(f"1 in the array is {numpyArray[1]}")
print(f"2 in the array is {numpyArray[2]}")
print(f"-1 in the array is {numpyArray[-1]}")

<class 'numpy.ndarray'>
The array is [1 2 3]
0 in the array is 1
1 in the array is 2
2 in the array is 3
-1 in the array is 3


In [10]:
numpyOnes = np.ones( (3,4),
                    dtype=np.int16 )
print(type(numpyOnes))
print(numpyOnes)
numpyOnes[0,2] = 7
print(numpyOnes)
print(numpyOnes[0,2])


<class 'numpy.ndarray'>
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 7 1]
 [1 1 1 1]
 [1 1 1 1]]
7


In [11]:
numpyFull = np.full( (4,5), "Hi")
print(type(numpyFull))
print(numpyFull)

<class 'numpy.ndarray'>
[['Hi' 'Hi' 'Hi' 'Hi' 'Hi']
 ['Hi' 'Hi' 'Hi' 'Hi' 'Hi']
 ['Hi' 'Hi' 'Hi' 'Hi' 'Hi']
 ['Hi' 'Hi' 'Hi' 'Hi' 'Hi']]


In [16]:
numpyArange = np.arange( 10, 100, 5)
print(type(numpyArange))
print(f"Numpy arrange takes 3 numbers, the starting number, what to go up to, than what interval to use, so (10, 20, 5) would be [ 10 15], and 10, 100, and 5 would be \n{numpyArange}.")

<class 'numpy.ndarray'>
Numpy arrange takes 3 numbers, the starting number, what to go up to, than what interval to use, so (10, 20, 5) would be [ 10 15], and 10, 100, and 5 would be 
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95].


In [22]:
numpyLinspace = np.linspace(0, 5/3, 6)
print(f"Numpy linspace has a type of {type(numpyLinspace)} and does this for 0, 5/3, and 6 \n{numpyLinspace}\nIt counts in thirds from 0 to 5/3 in a set amount of equal intervals, in this case 6.")

Numpy linspace has a type of <class 'numpy.ndarray'> and does this for 0, 5/3, and 6 
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
It counts in thirds from 0 to 5/3 in a set amount of equal intervals, in this case 6.


In [24]:
numpyRandom = np.random.rand(2,3)
print(f"Numpy random.rand has a type of {type(numpyRandom)} and does this for 2,3\n {numpyRandom}\n it takes (x,y), x is the number of arrays and 3 is how many items in each array.")

Numpy random.rand has a type of <class 'numpy.ndarray'> and does this for 2,3
 [[0.79592882 0.68095655 0.51245855]
 [0.12521132 0.40848576 0.53237685]]


In [27]:
numpyEmpty = np.empty((2,3))
print(f"The type of numpyEmpty is {type(numpyEmpty)} and it does this for ((2,3))\n{numpyEmpty}\n it  makes ((x,y)) x arrays with 3 items, each under 1.")

The type of numpyEmpty is <class 'numpy.ndarray'> and it does this for ((2,3))
[[0.79592882 0.68095655 0.51245855]
 [0.12521132 0.40848576 0.53237685]]
 it  makes ((x,y)) x arrays with 3 items, each under 1.


Attributes of a numpy object

1. Ndim
2. Shape
3. Size
4. Dtype
5. Itemsize
6. Reshape